# Generated by Django 5.2.6 on 2025-10-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0012_remove_reserva_unique_usuario_vuelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='clase',
            field=models.CharField(choices=[('economica', 'Económica'), ('primera', 'Primera Clase')], default='economica', max_length=20),
        ),
    ]
