# Generated by Django 5.2.6 on 2025-10-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0013_reserva_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo',
            field=models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('BLOQUEADA', 'Bloqueada'), ('VENCIDA', 'Vencida')], max_length=10),
        ),
    ]
