# Generated by Django 5.2.6 on 2025-10-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0014_alter_tarjeta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida'), ('confirmada', 'Confirmada')], default='activa', max_length=10),
        ),
    ]
