# Generated by Django 5.2.6 on 2025-10-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0015_tarjeta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
