# Generated by Django 5.2.6 on 2025-10-30 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0016_compra_monto_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaPasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('contacto_nombre', models.CharField(max_length=150)),
                ('contacto_telefono', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_usuario_vuelo_activa',
        ),
        migrations.AddField(
            model_name='reserva',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservapasajero',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasajeros', to='aerolinea.reserva'),
        ),
        migrations.AddConstraint(
            model_name='reservapasajero',
            constraint=models.UniqueConstraint(fields=('documento', 'reserva'), name='unique_pasajero_por_reserva'),
        ),
    ]
