# Generated by Django 5.2.6 on 2025-10-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0017_reservapasajero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='activo', max_length=20),
        ),
    ]
