# Generated by Django 5.2.6 on 2025-11-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0018_vuelo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservapasajero',
            name='asiento',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
