# Generated by Django 5.2.6 on 2025-11-17 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0019_reservapasajero_asiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='aerolinea.reserva'),
        ),
    ]
