# Generated by Django 5.2.6 on 2025-11-18 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0020_compra_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], default='activa', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida'), ('confirmada', 'Confirmada'), ('pendiente_reubicacion', 'Pendiente de Reubicacion')], default='activa', max_length=50),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida'), ('confirmada', 'Confirmada')], default='activa', max_length=50),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='activo', max_length=50),
        ),
        migrations.CreateModel(
            name='Reubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada')], default='pendiente', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.reserva')),
                ('vuelo_cancelado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelado', to='aerolinea.vuelo')),
                ('vuelo_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reubicado', to='aerolinea.vuelo')),
            ],
        ),
    ]
