# Generated by Django 5.2.6 on 2025-11-26 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0021_alter_compra_estado_alter_reserva_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='tipo_trayecto',
            field=models.CharField(default='ida', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='vuelo_regreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_regreso', to='aerolinea.vuelo'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_trayecto',
            field=models.CharField(choices=[('ida', 'Solo ida'), ('ida_vuelta', 'Ida y vuelta')], default='ida', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='vuelo_regreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_regreso', to='aerolinea.vuelo'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='activa', max_length=50),
        ),
    ]
