# Generated by Django 5.2.6 on 2025-11-26 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0022_compra_tipo_trayecto_compra_vuelo_regreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tipo_trayecto',
            field=models.CharField(choices=[('ida', 'Solo ida'), ('ida_vuelta', 'Ida y Vuelta')], default='ida', max_length=15),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_ida', to='aerolinea.vuelo'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='vuelo_regreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_regreso', to='aerolinea.vuelo'),
        ),
    ]
