# Generated by Django 5.2.6 on 2025-11-26 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0023_alter_reserva_tipo_trayecto_alter_reserva_vuelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='costo_maleta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='monto_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='recargo_clase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reserva',
            name='incluye_maleta',
            field=models.BooleanField(default=False),
        ),
    ]
