# Generated by Django 5.2.6 on 2025-11-27 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0024_compra_costo_maleta_compra_creado_compra_monto_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='fecha_checkin',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkin',
            name='pasajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aerolinea.reservapasajero'),
        ),
    ]
