# Generated by Django 5.2.6 on 2025-11-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0025_checkin_fecha_checkin_checkin_pasajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservapasajero',
            name='check_in_realizado',
            field=models.BooleanField(default=False),
        ),
    ]
