# Generated by Django 5.2.6 on 2025-11-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0026_reservapasajero_check_in_realizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservapasajero',
            name='asiento_cambiado',
            field=models.BooleanField(default=False),
        ),
    ]
