# Generated by Django 5.2.6 on 2025-12-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0027_reservapasajero_asiento_cambiado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion_facturacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
