# Generated by Django 5.2.6 on 2025-12-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0029_promocion_usuario_suscrito_promos_suscripcionpromos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='descuento_porcentaje',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='promocion_activa',
            field=models.BooleanField(default=False),
        ),
    ]
