# Generated by Django 5.2.6 on 2025-12-07 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0030_vuelo_descuento_porcentaje_vuelo_promocion_activa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('INFO', 'Información'), ('PROMO', 'Promoción'), ('ALERTA', 'Alerta')], max_length=10)),
                ('descuento_porcentaje', models.PositiveIntegerField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Promocion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='suscrito_promos',
            new_name='suscrito_noticias',
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='descuento_porcentaje',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de descuento aplicado al vuelo'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='vuelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerolinea.vuelo'),
        ),
        migrations.DeleteModel(
            name='SuscripcionPromos',
        ),
    ]
