# Generated by Django 5.2.6 on 2025-12-09 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0031_noticia_delete_promocion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioHistoricoVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.vuelo')),
            ],
        ),
    ]
