# Generated by Django 5.2.6 on 2025-12-09 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0032_preciohistoricovuelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.CharField(max_length=50)),
                ('estado_nuevo', models.CharField(max_length=50)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='aerolinea.vuelo')),
            ],
        ),
    ]
